//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ModeloData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanCovid_DBEntities : DbContext
    {
        public BanCovid_DBEntities()
            : base("name=BanCovid_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Beneficiario> Tbl_Beneficiario { get; set; }
        public virtual DbSet<Tbl_BeneficiarioEstado> Tbl_BeneficiarioEstado { get; set; }
        public virtual DbSet<Tbl_Caja> Tbl_Caja { get; set; }
        public virtual DbSet<Tbl_Cliente> Tbl_Cliente { get; set; }
        public virtual DbSet<Tbl_Cuenta> Tbl_Cuenta { get; set; }
        public virtual DbSet<Tbl_OperacionCaja> Tbl_OperacionCaja { get; set; }
        public virtual DbSet<Tbl_OperacionCajaTipo> Tbl_OperacionCajaTipo { get; set; }
        public virtual DbSet<Tbl_Perfil> Tbl_Perfil { get; set; }
        public virtual DbSet<Tbl_TipoTransaccion> Tbl_TipoTransaccion { get; set; }
        public virtual DbSet<Tbl_Transaccion> Tbl_Transaccion { get; set; }
        public virtual DbSet<Tbl_Usuario> Tbl_Usuario { get; set; }
        public virtual DbSet<Tbl_EstadoUsuario> Tbl_EstadoUsuario { get; set; }
    }
}
