//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ModeloData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Beneficiario
    {
        public int CuentaId { get; set; }
        public int CuentaDestinoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public short Estado { get; set; }
    
        public virtual Tbl_Cuenta Tbl_Cuenta { get; set; }
        public virtual Tbl_Cuenta Tbl_Cuenta1 { get; set; }
        public virtual Tbl_BeneficiarioEstado Tbl_BeneficiarioEstado { get; set; }
    }
}
