//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ModeloData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Usuario
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Cedula { get; set; }
        public short Perfil_Id { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public short Estado { get; set; }
    
        public virtual Tbl_Cliente Tbl_Cliente { get; set; }
        public virtual Tbl_EstadoUsuario Tbl_EstadoUsuario { get; set; }
        public virtual Tbl_Perfil Tbl_Perfil { get; set; }
    }
}
