//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ModeloData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Transaccion
    {
        public long Id { get; set; }
        public short TipoTransaccionId { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CuentaId { get; set; }
        public int CajaId { get; set; }
    }
}
