//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ModeloData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BeneficiarioEstado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_BeneficiarioEstado()
        {
            this.Tbl_Beneficiario = new HashSet<Tbl_Beneficiario>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Beneficiario> Tbl_Beneficiario { get; set; }
    }
}
