//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ModeloData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OperacionCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_OperacionCaja()
        {
            this.Tbl_Transaccion = new HashSet<Tbl_Transaccion>();
        }
    
        public long Id { get; set; }
        public short TipoId { get; set; }
        public int CajaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public bool Estado { get; set; }
    
        public virtual Tbl_Caja Tbl_Caja { get; set; }
        public virtual Tbl_OperacionCajaTipo Tbl_OperacionCajaTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transaccion> Tbl_Transaccion { get; set; }
    }
}
