//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ModeloData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Beneficiario
    {
        public int IdCuenta { get; set; }
        public int IdCuentaDestino { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public short Estado { get; set; }
    }
}
