//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ModeloData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OperacionCajaTipo
    {
        public short Id { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
    }
}
