//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ModeloData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Transaccion
    {
        public long Id { get; set; }
        public short TipoTransaccionId { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CuentaId { get; set; }
        public Nullable<int> CuentaDestinoId { get; set; }
        public Nullable<long> OperacionCajaId { get; set; }
        public short Estado { get; set; }
    
        public virtual Tbl_Cuenta Tbl_Cuenta { get; set; }
        public virtual Tbl_Cuenta Tbl_Cuenta1 { get; set; }
        public virtual Tbl_EstadoTransaccion Tbl_EstadoTransaccion { get; set; }
        public virtual Tbl_OperacionCaja Tbl_OperacionCaja { get; set; }
        public virtual Tbl_TipoTransaccion Tbl_TipoTransaccion { get; set; }
    }
}
